### PR TITLE
#162948831 Integrate travis and coveralls 

### PR DESCRIPTION
**Pull request by kwameasiago**
#### What does this PR do?
Integrate Travis and Coveralls

#### Description of Task to be completed?
Integrated Travis to github repo
Integrated Coveralls to github repo
Added a .travis.yml file

#### How should this be manually tested?
navigate to gihub travis [link](https://travis-ci.org/andela/ah-django-unchained) to view the links

#### Any background context you want to provide?
Travis is primarily used to automate test and ensure they are passing when a push is made to the github repo

#### What are the relevant pivotal tracker stories?
[#162948831](https://www.pivotaltracker.com/story/show/162948831)

### CODE REVIEW

**Review by Georgeygigz — APPROVED** [review]

**Review by KMaina — APPROVED** [review]
Looks good to me

**Comment by ignatiusukwuoma** [comment]
Is coveralls not supposed to have a badge?

**Comment by kwameasiago** [comment]
@ignatiusukwuoma Yes it does but it needs the Travis to build first. I was waiting for @MaggieChege test to be merged to master

**Comment by ignatiusukwuoma** [comment]
What else needs to be done on this PR before it's merged to master?

**Comment by kwameasiago** [comment]
@ignatiusukwuoma nothing else.

**Pull request merged**
